# Citizens CMD Plugin by Mateus Moreira
# @LichtHund
# Version ${project.version}
# Wiki: https://github.com/ipsk/CitizensCMD/wiki
# GitHub: https://github.com/ipsk/CitizensCMD
# Spigot: https://www.spigotmc.org/resources/citizens-cmd.30224/

#
# Enables Checking for update.
check-updates: true
#
# Available languages EN, PT, BG, RO, NO, CH
lang: 'en'
#
# The default npc cooldown in seconds
default-cooldown: 0
#
# When using a NPC with price, true means that to confirm the use the player needs to seek or press shift
shift-confirm: true
#
# Select cooldown display format, SHORT = 3m 3s | MEDIUM = 3 min 3 sec | FULL - 3 minutes 3 seconds
cooldown-time-display: MEDIUM